### ISSUE TITLE
Telemetry for Separate Members and Participants

### ISSUE THREAD

**Issue by crspeller** [mattermost/mattermost-plugin-playbooks#1433]
Placeholder ticket for telemetry desired for feedback on separation of members and participants.

**Comment by itao** [comment]
The questions I'd like to be answer are:
1. Do people find it useful to identify participants?
2. Do people tend to add themselves or be added? otherwise (either by another user or automatically by the playbook)

I think the charts that'd answer these questions are:
1. Distribution of runs each month by total number of participants in a stacked percentage bar chart. Runs with 1 participant means this feature isn't used, and this'd give us an idea of how many participants tend to be in runs (ie. 35% of runs last month have over 20 participants).
2. Number of times participants were added each week in stacked bar chart, separated by `Added themselves`, `Added by another user`, `Added by playbook`

Would love your feedback if this sounds reasonable and guidance on how the telemetry events should be instrumented.

**Comment by trilopin** [comment]
Regarding point 2 (added themselves), I've [added events](https://github.com/mattermost/mattermost-plugin-playbooks/pull/1484/files) _playbookrun_participate_ and _playbookrun_leave_ which carry information about where the action has been done (playbooks-lhs, run_details, channels-rhs) 

As soon as RunDetails-Participants flow  moves forward, we could add the events like:
- playbookrun_addparticipant
- playbookrun_removeparticipant
