### ISSUE TITLE
Figure out why the app bar icon appears "white"

### ISSUE THREAD

**Issue by lieut-data** [mattermost/mattermost-plugin-playbooks#1817]
![Image](https://user-images.githubusercontent.com/1023171/221037914-93452bc7-bf3e-45ea-a870-dee10adb613f.png)

**Comment by trilopin** [comment]
@lieut-data this was the status of my icon before I push the commit [6bc263fa](https://github.com/mattermost/mattermost-plugin-playbooks/commit/6bc263fa40f7c8dee82657ed6849805233323c3c) to mpa-playbooks and restarted mattermost-webapp (not sure why, but I did it).

Current status
![Screenshot 2023-02-24 at 09 20 06](https://user-images.githubusercontent.com/4096774/221128237-cfa15b15-6a54-4e3a-9ef5-399281f4866b.png)


I wonder why is failing on your side...

**Comment by lieut-data** [comment]
@trilopin, indeed I remain as flummoxed as you! Before your change, the e2e tests were failing to find the component, now they pass, but the SVG being rendered remains white. It's entirely possible it's an artifact with my local setup...

<img width="782" alt="image" src="https://user-images.githubusercontent.com/1023171/221190004-5567fc53-f7c9-4951-8b00-2de9c1be6c7b.png">

**Comment by trilopin** [comment]
I still can not reproduce this problem. From [the app bar code](https://github.com/mattermost/mattermost-webapp/blob/master/components/app_bar/app_bar_plugin_component.tsx#L67) I understand that you still have an unreachable URL, and that's why it renders as empty with `icon__plugin`classname.

My only guess is that we (you and me) are building playbooks in a different way.

**Comment by lieut-data** [comment]
Traced this a caching issue, so it's not specific to this effort (but may be something to evaluate in the larger monorepo effort.)

**Comment by lieut-data** [comment]
See https://community.mattermost.com/core/pl/te35jbxnn7r9i8cf7aujp7jkzh for discussion.
